### ISSUE TITLE
mimetype

### ISSUE THREAD

**Issue by nelsonlarocca** [ARozar/multer-google-storage#3]
is there any way to set the content type,  at least the mimetype to be equal to one of the uploaded file ?

**Comment by vitorsilvalima** [comment]
Hi @nelsonlarocca I dont think there is a way in the current implementation. However, I now how to implement this feature so I will open a pr in the next few days

**Comment by vitorsilvalima** [comment]
https://github.com/ARozar/multer-google-storage/pull/5

**Comment by vitorsilvalima** [comment]
@ARozar can you please review this pr. It adds the file content type information

**Comment by rparpa** [comment]
Hello. I'm in the same case, and saw the first PR before making my own #8. Hope it will do the trick !
