### ISSUE TITLE
@google-cloud/storage has no exported member 'ConfigurationObject'.

### ISSUE THREAD

**Issue by madhavan-sundararaj** [ARozar/multer-google-storage#7]
After running the code i am getting the following error. 
@google-cloud/storage has no exported member 'ConfigurationObject'.

Code as follows:
import * as  multer from 'multer';
import MulterGoogleCloudStorage from 'multer-google-storage';

const uploadHandler = multer({
  storage: new MulterGoogleCloudStorage({
    bucket: 'my-bucket',
    projectId: 'testing',
    keyFilename: '/Applications/file.json',
  })
});

module.exports = uploadHandler;

implemented app.post in service.ts

**Comment by sainisagar310** [comment]
+1

I am facing the same issue. Have you got any solution for that?

**Comment by madhavan-sundararaj** [comment]
Yes, I used `const multerGoogleStorage = require('multer-google-storage');` instead of `import MulterGoogleCloudStorage from 'multer-google-storage';`

Cheers

**Comment by xahanix** [comment]
I'm facing the same issue.
But I shouldn't have to update a node_modules so this have to be default.

**Comment by raj2399** [comment]
This was happening when I added @google-cloud/storage into my project, and the solution was to add @types/google-cloud__storage. 
So the only thing you need to do is run: ''yarn add @types/google-cloud__storage'', this works fine for me.

**Comment by raj2399** [comment]
This was happening when I added @google-cloud/storage into my project, and the solution was to add @types/google-cloud__storage. So the only thing you need to do is run:
npm add @types/google-cloud__storage'', this works fine for me.
